"use client";
import {useState,useEffect,useRef,useCallback} from 'react';
import {Plus,Minus,Utensils,ArrowUpRight,Search,SlidersHorizontal,Copy,Check,RotateCcw,Trash2,BookOpen,Info,ChevronRight} from 'lucide-react';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogHeader,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogCancel,AlertDialogAction} from '@/components/ui/alert-dialog';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Toaster} from '@/components/ui/sonner';
import {Skeleton} from '@/components/ui/skeleton';
import {toast} from 'sonner';
import {menu,coverage,restaurants,totals,round,localDate,type Food,type Line,type Meal,type Macros} from '@/lib/menu';
const keys=['calories','protein','carbs','fat'] as const;
const labels={calories:'Calories',protein:'Protein',carbs:'Carbs',fat:'Fat'};
function MacroRow({value}:{value:Macros}){return <div className="macro-row">{(['protein','carbs','fat'] as const).map(k=><div key={k} className={'macro '+k}><span>{labels[k]}</span><strong>{round(value[k])}<small> g</small></strong></div>)}</div>}
function mealText(m:Meal){const t=totals(m.items);return `${m.name} — ${Math.round(t.calories)} calories | ${round(t.protein)}g protein | ${round(t.carbs)}g carbs | ${round(t.fat)}g fat\n${m.items.map(i=>`${i.quantity} × ${i.name} (${i.serving})${i.quality!=='published'?' [estimate]':''}`).join('\n')}`;}
export default function Home(){
 const [restaurant,setRestaurant]=useState('canes'),[search,setSearch]=useState(''),[tab,setTab]=useState('menu'),[category,setCategory]=useState('all'),[visibleCount,setVisibleCount]=useState(30);
 const [items,setItems]=useState<Line[]>([]),[name,setName]=useState(''),[period,setPeriod]=useState('Lunch'),[date,setDate]=useState('');
 const [meals,setMeals]=useState<Meal[]>([]),[recent,setRecent]=useState<Meal[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[signedOut,setSignedOut]=useState(false),[saving,setSaving]=useState(false);
 const [editor,setEditor]=useState<Line|null>(null),[editorMode,setEditorMode]=useState<'add'|'edit'>('add'),[info,setInfo]=useState<Food|null>(null),[toDelete,setToDelete]=useState<Meal|null>(null),[deleting,setDeleting]=useState(false);
 const requestRef=useRef(0),saveLock=useRef(false),saveId=useRef<string|null>(null);const current=restaurants.find(r=>r.id===restaurant)!;
 const total=totals(items),daily=totals(meals.flatMap(m=>m.items));const estimated=items.some(i=>i.quality!=='published');
 useEffect(()=>setDate(localDate()),[]);
 const load=useCallback(async()=>{if(!date)return;const sequence=++requestRef.current;setLoading(true);setError('');try{const res=await fetch('/api/meals?date='+date);const data=await res.json() as {error?:string;meals:Meal[];recent:Meal[]};if(sequence!==requestRef.current)return;if(!res.ok){setSignedOut(res.status===401);throw new Error(data.error||'Your log could not load.')}setSignedOut(false);setMeals(data.meals);setRecent(data.recent);}catch(e){if(sequence===requestRef.current){setMeals([]);setError(e instanceof Error?e.message:'Your log could not load.')}}finally{if(sequence===requestRef.current)setLoading(false)}},[date]);
 useEffect(()=>{void load();return()=>{requestRef.current++}},[load]);
 useEffect(()=>{saveId.current=null},[items,name,period,date]);
 const add=useCallback((food:Food,quantity=1)=>{setItems(old=>{const found=old.find(i=>i.id===food.id&&i.quality===food.quality);return found?old.map(i=>i.lineId===found.lineId?{...i,quantity:Math.min(100,round(i.quantity+quantity))}:i):[...old,{...food,quantity,lineId:crypto.randomUUID()}]});},[]);
 function changeQty(id:string,value:number){setItems(old=>old.map(i=>i.lineId===id?{...i,quantity:Math.min(100,Math.max(0,round(value)))}:i).filter(i=>i.quantity>0))}
 function customize(food?:Food,line?:Line){setEditorMode(line?'edit':'add');setEditor(line?{...line}:{...(food??{id:crypto.randomUUID(),restaurant,name:'',serving:'1 serving',category:'Custom options',calories:0,protein:0,carbs:0,fat:0,quality:'custom' as const,source:'',note:'User-entered nutrition. Not verified by the restaurant.'}),quantity:1,lineId:crypto.randomUUID()})}
 async function save(){if(saveLock.current||!items.length||!date)return;saveLock.current=true;setSaving(true);const id=saveId.current??crypto.randomUUID();saveId.current=id;try{const res=await fetch('/api/meals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id,name:mealName,date,period,items})});const data=await res.json() as {error?:string;meals:Meal[];recent:Meal[]};if(!res.ok){if(res.status===401)setSignedOut(true);throw new Error(data.error||'Could not save your meal.')}setItems([]);setName('');saveId.current=null;toast.success('Meal added to your daily log.');await load();}catch(e){toast.error(e instanceof Error?e.message:'Could not save. Your meal is still here.')}finally{saveLock.current=false;setSaving(false)}}
 async function remove(){if(!toDelete||deleting)return;setDeleting(true);try{const res=await fetch('/api/meals?id='+toDelete.id,{method:'DELETE'});const data=await res.json() as {error?:string;meals:Meal[];recent:Meal[]};if(!res.ok)throw new Error(data.error||"Request failed.");setToDelete(null);toast.success('Meal removed.');await load()}catch(e){toast.error(e instanceof Error?e.message:'Could not remove meal.')}finally{setDeleting(false)}}
 function reuse(m:Meal){setItems(old=>[...old,...m.items.map(i=>({...i,lineId:crypto.randomUUID()}))]);if(!items.length){setName(m.name);setPeriod(m.period)}setTab('menu');toast.success('Added to your meal. Review it, then log it.');document.getElementById('meal-builder')?.scrollIntoView({behavior:'smooth',block:'start'});}
 async function copy(m:Meal){try{await navigator.clipboard.writeText(mealText(m));toast.success('Meal summary copied.')}catch{toast.error('Clipboard unavailable. You can select and copy the totals directly.')}}
 useEffect(()=>{const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();const defs=[{name:'list_restaurant_foods',description:'List the available food catalog, including portions, macros and source quality.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({restaurants,foods:menu})},{name:'add_foods_to_meal',description:'Stage catalog foods in the visible meal builder. Does not save a meal to the daily log.',inputSchema:{type:'object',properties:{items:{type:'array',minItems:1,maxItems:30,items:{type:'object',properties:{id:{type:'string'},quantity:{type:'number',exclusiveMinimum:0,maximum:100}},required:['id','quantity'],additionalProperties:false}}},required:['items'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const value=input as {items?:{id:string;quantity:number}[]};if(!Array.isArray(value?.items)||!value.items.length||value.items.length>30)throw new Error('Provide 1–30 foods.');const resolved=value.items.map(i=>{const f=menu.find(f=>f.id===i.id);if(!f||typeof i.quantity!=='number'||!Number.isFinite(i.quantity)||i.quantity<=0||i.quantity>100)throw new Error('Invalid food or quantity.');return {f,q:i.quantity}});resolved.forEach(({f,q})=>add(f,q));await new Promise(requestAnimationFrame);return {staged:resolved.length,saved:false}}}];for(const tool of defs){try{Promise.resolve(context.registerTool(tool,{signal:lifecycle.signal})).catch(console.error)}catch(e){console.error(e)}}return()=>lifecycle.abort()},[add]);
 const restaurantFoods=menu.filter(f=>f.restaurant===restaurant);
 const categories=[...new Set(restaurantFoods.map(f=>f.category))];
 const filtered=restaurantFoods.filter(f=>(category==='all'||f.category===category)&&`${f.name} ${f.category} ${f.serving}`.toLowerCase().includes(search.toLowerCase()));
 const mealName=name.trim()||(new Set(items.map(i=>i.restaurant)).size>1?'My mixed meal':`${restaurants.find(r=>r.id===(items[0]?.restaurant??restaurant))?.name??current.name} meal`);
 return <><Toaster theme="light" position="bottom-right"/><header className="topbar"><a className="brand" href="/"><span className="brand-icon"><Utensils size={21}/></span>meal fold<span className="brand-period">.</span></a><span className="top-note">YOUR FOOD, ALL ACCOUNTED FOR</span><a className="personal" href="#daily-log"><BookOpen size={15}/> My food log</a></header><main className="workspace"><div className="page-heading"><div><p className="eyebrow">THE DAILY MENU</p><h1>What did you eat?</h1><p className="subheading">Your usual order. Your little changes. One simple entry.</p></div><label className="date-control">Log date<input type="date" aria-label="Log date" value={date} onChange={e=>{if(e.target.value)setDate(e.target.value)}}/></label></div>
 <div className="restaurant-grid">{restaurants.map((r,i)=><button key={r.id} className={'restaurant '+(r.id===restaurant?'selected':'')} aria-pressed={r.id===restaurant} onClick={()=>{setRestaurant(r.id);setSearch('');setCategory('all');setVisibleCount(30);setTab('menu')}}><span className={'restaurant-monogram mark-'+i}>{r.mark}</span><span>{r.name}<small>{r.subtitle}</small></span>{r.id===restaurant&&<span className="selected-indicator"><Check size={13}/></span>}</button>)}</div>
 <div className="builder-grid" id="meal-builder"><section className="menu-panel"><div className="section-heading"><h2>{current.name}</h2><span className="muted">{menu.filter(f=>f.restaurant===restaurant).length} menu items</span></div>{restaurant==='canes'&&<div className="food-banner"><img alt="Breaded Raising Cane’s chicken fingers with fries, toast and sauce" src="https://images.prismic.io/raisingcanes/Z094gJbqstJ98AS2_combos.jpg?auto=format%2Ccompress&fit=max&h=499&rect=0%2C360%2C1200%2C480&w=1247"/><div><span className="eyebrow">MAKE IT YOURS</span><h3>Count the sauce, too.</h3></div></div>}
 <Tabs value={tab} onValueChange={setTab}><div className="menu-toolbar"><TabsList variant="line"><TabsTrigger value="menu">Menu</TabsTrigger><TabsTrigger value="recent">Recent meals</TabsTrigger></TabsList><button className="text-button" onClick={()=>customize()}><Plus size={15}/> Custom item</button></div><TabsContent value="menu"><details className="coverage-note"><summary>Nutrition coverage · {restaurantFoods.length} entries</summary><p>{coverage.find(c=>c.restaurant===restaurant)?.scope}</p><p>Sources checked September 21, 2026. Published dates and recipe assumptions are listed with each item.</p></details><div className="search-box"><Search size={17}/><input aria-label="Search menu" placeholder="Search a drink, food, or size…" value={search} onChange={e=>{setSearch(e.target.value);setVisibleCount(30)}}/></div><div className="catalog-filters"><label>Category<select aria-label="Menu category" value={category} onChange={e=>{setCategory(e.target.value);setVisibleCount(30)}}><option value="all">All categories</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></label><span>{filtered.length} matches</span></div>{['leaves','bean','starbucks'].includes(restaurant)&&<p className="inline-note">Choose the exact size and hot or iced recipe. Add toppings separately. Milk and sweetness changes are estimates—use Customize to adjust your order.</p>}{restaurant==='chipotle'&&<p className="inline-note">Build your bowl ingredient by ingredient. Set protein to 2 for double, or rice to 0.5 for a half portion.</p>}{restaurant==='panda'&&<p className="inline-note">Half-and-half side? Add each side, then set each quantity to 0.5.</p>}{restaurant==='kura'&&<p className="inline-note">Values are per listed menu serving, not per individual sushi piece. Match your order to the source.</p>}
 {filtered.slice(0,visibleCount).map(f=><article className={'food-row '+(f.category==='Custom options'?'special-row':'')} key={f.id}><div><div className="food-name"><h3>{f.name}</h3>{f.category==='Custom options'&&<span className="badge">Custom option</span>}</div><p>{f.serving}</p><div className="food-meta"><span>{f.protein}g P <b>·</b> {f.carbs}g C <b>·</b> {f.fat}g F</span><button className={'source-button '+(f.quality==='estimate'?'estimated':'')} onClick={()=>setInfo(f)}>{f.quality==='published'?<Check size={12}/>:<Info size={12}/>} {f.quality==='published'?'Published':'Estimate'}</button></div></div><div className="food-cal">{f.quality==='estimate'?'~':''}{f.calories}<small>cal</small></div><div className="food-actions"><button className="add-button" aria-label={'Add '+f.name} onClick={()=>add(f)}><Plus size={19}/></button><button className="edit-food" aria-label={'Customize '+f.name} onClick={()=>customize(f)}><SlidersHorizontal size={14}/></button></div></article>)}{filtered.length>visibleCount&&<button className="load-more secondary-button" onClick={()=>setVisibleCount(n=>n+30)}>Show 30 more items ({filtered.length-visibleCount} remaining)</button>}{!filtered.length&&<div className="inline-empty">No matching items. Add a custom item with the nutrition you know.</div>}<p className="menu-note">Tap Published or Estimate for full nutrition facts, source dates and assumptions. Recipes and availability vary by location.</p></TabsContent>
 <TabsContent value="recent">{loading?<div className="loading-list"><Skeleton className="h-20"/><Skeleton className="h-20"/></div>:error?<p className="inline-empty">{error}</p>:!recent.length?<div className="inline-empty"><RotateCcw size={25}/><h3>Your usuals will live here.</h3><p>Log a meal once, then add it again with a click.</p></div>:recent.map(m=><div className="recent-row" key={m.id}><div><h3>{m.name}</h3><p>{m.date} · {Math.round(totals(m.items).calories)} cal</p></div><button className="text-button" onClick={()=>reuse(m)}>Add again <Plus size={16}/></button></div>)}</TabsContent></Tabs></section>
 <aside className="receipt" aria-label="Meal builder"><div className="receipt-title"><span className="eyebrow">ONE MEAL. ALL THE DETAILS.</span><h2>Your meal <span className="item-count">{items.length}</span></h2></div>{!items.length?<div className="meal-empty"><Utensils size={30}/><h3>Start with a favorite.</h3><p>Add items from the menu to see your meal come together.</p></div>:<><div className="receipt-items">{items.map(i=><div className="receipt-line" key={i.lineId}><div className="line-heading"><button onClick={()=>customize(undefined,i)} className="line-name">{i.name} <SlidersHorizontal size={12}/></button><span>{i.quality!=='published'?'~':''}{Math.round(i.calories*i.quantity)} cal</span></div><small>{i.serving}{i.quality!=='published'?' · Estimated':''}</small><div className="quantity-row"><div className="stepper"><button aria-label={'Decrease '+i.name} onClick={()=>changeQty(i.lineId,i.quantity-.5)}><Minus size={12}/></button><input aria-label={'Quantity of '+i.name} type="number" min="0.1" max="100" step="0.1" value={i.quantity} onChange={e=>{const n=Number(e.target.value);if(e.target.value&&Number.isFinite(n))changeQty(i.lineId,n)}}/><button aria-label={'Increase '+i.name} onClick={()=>changeQty(i.lineId,i.quantity+.5)}><Plus size={12}/></button></div><button className="remove-line" aria-label={'Remove '+i.name} onClick={()=>changeQty(i.lineId,0)}><Trash2 size={13}/></button></div></div>)}</div><label className="field meal-name">Meal name<input maxLength={160} placeholder={mealName} value={name} onChange={e=>setName(e.target.value)}/></label></>}
 <div aria-live="polite"><div className="receipt-total"><span>{estimated?'Estimated calories':'Total calories'}</span><strong>{Math.round(total.calories).toLocaleString()}<small> cal</small></strong></div><MacroRow value={total}/></div>{estimated&&<p className="estimate-note"><Info size={14}/> Includes estimated or user-entered nutrition.</p>}<div className="log-controls"><Select value={period} onValueChange={setPeriod}><SelectTrigger aria-label="Meal type"><SelectValue/></SelectTrigger><SelectContent>{['Breakfast','Lunch','Dinner','Snack'].map(p=><SelectItem key={p} value={p}>{p}</SelectItem>)}</SelectContent></Select><span>{date?new Date(date+'T12:00:00').toLocaleDateString(undefined,{month:'short',day:'numeric'}):'Choose date'}</span></div><button className="primary-button" disabled={!items.length||saving||!date} onClick={save}>{saving?'Saving meal…':'Log this meal'} {!saving&&<ChevronRight size={18}/>}</button>{items.length>0&&<button className="copy-button" onClick={()=>copy({id:'draft',name:mealName,date,period,items})}><Copy size={14}/> Copy condensed summary</button>}<p className="receipt-foot">Saved to your private food log.</p></aside></div>
 <section className="daily-log" id="daily-log"><div className="section-heading"><div><p className="eyebrow">EVERY MEAL ADDS UP</p><h2>{date===localDate()?'Today’s log':'Daily log'}</h2></div><span className="muted">{loading?'Loading…':`${meals.length} ${meals.length===1?'meal':'meals'} logged`}</span></div>{error?<div className="error-state"><p>{error}</p>{signedOut?<a className="primary-button" href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in to your log</a>:<button className="secondary-button" onClick={load}>Try again</button>}</div>:<><div className="daily-totals">{keys.map(k=><div key={k}><span>{labels[k]}</span>{loading?<Skeleton className="h-8 w-20 mt-2"/>:<strong>{k==='calories'?Math.round(daily[k]).toLocaleString():round(daily[k])}<small>{k==='calories'?' cal':' g'}</small></strong>}</div>)}</div>{!loading&&(meals.length?meals.map(m=>{const t=totals(m.items);return <article className="logged-meal" key={m.id}><div className="logged-icon"><Utensils size={18}/></div><div className="logged-description"><span className="meal-period">{m.period}</span><h3>{m.name}</h3><p>{m.items.map(i=>`${i.quantity} × ${i.name}`).join(' · ')}</p><div className="logged-macros">{round(t.protein)}g protein · {round(t.carbs)}g carbs · {round(t.fat)}g fat{m.items.some(i=>i.quality!=='published')?' · Includes estimates':''}</div></div><strong className="logged-calories">{Math.round(t.calories)}<small> cal</small></strong><div className="logged-actions"><button aria-label={'Repeat '+m.name} onClick={()=>reuse(m)}><RotateCcw size={17}/></button><button aria-label={'Copy '+m.name} onClick={()=>copy(m)}><Copy size={16}/></button><button aria-label={'Delete '+m.name} onClick={()=>setToDelete(m)}><Trash2 size={16}/></button></div></article>}):<div className="log-empty"><BookOpen size={22}/><p>No meals logged for this date yet. Build your first meal above.</p></div>)}</>}</section><footer className="footer"><span>Meal Fold · Made for your real-world orders.</span><span>Nutrition is a guide; restaurant portions vary.</span></footer></main>
 <Dialog open={!!editor} onOpenChange={o=>{if(!o)setEditor(null)}}><DialogContent className="editor-dialog"><DialogHeader><DialogTitle>{editorMode==='edit'?'Edit meal item':'Customize an item'}</DialogTitle><DialogDescription>Nutrition is per serving. Changing the name, portion, or macros marks the item as your estimate.</DialogDescription></DialogHeader>{editor&&<form onSubmit={e=>{e.preventDefault();if(!editor.name.trim()||!editor.serving.trim())return;if(editorMode==='edit')setItems(old=>old.map(i=>i.lineId===editor.lineId?editor:i));else setItems(old=>[...old,editor]);setEditor(null)}}><label className="field">Item name<input required maxLength={160} value={editor.name} onChange={e=>setEditor({...editor,name:e.target.value,quality:'custom'})}/></label><label className="field">Serving size<input required maxLength={160} value={editor.serving} onChange={e=>setEditor({...editor,serving:e.target.value,quality:'custom'})}/></label><div className="nutrition-inputs">{keys.map(k=><label className="field" key={k}>{labels[k]}{k!=='calories'?' (g)':''}<input type="number" required min="0" max="20000" step="0.1" value={editor[k]} onChange={e=>setEditor({...editor,[k]:e.target.value===''?'':Number(e.target.value),quality:'custom'})}/></label>)}</div><label className="field">How many servings?<input type="number" min="0.1" max="100" step="0.1" required value={editor.quantity} onChange={e=>setEditor({...editor,quantity:e.target.value===''?'' as unknown as number:Number(e.target.value)})}/></label><p className="editor-note">{editor.quality==='published'?'Published nutrition; quantities scale proportionally.':editor.quality==='custom'?'Your estimate. Adjust all affected macros when removing or adding ingredients.':editor.note}</p><button className="primary-button" type="submit">{editorMode==='edit'?'Update item':'Add to meal'}</button></form>}</DialogContent></Dialog>
 <Dialog open={!!info} onOpenChange={o=>{if(!o)setInfo(null)}}><DialogContent className="nutrition-dialog"><DialogHeader><DialogTitle>{info?.name}</DialogTitle><DialogDescription>{info?.quality==='published'?'Restaurant-published nutrition':'Estimated nutrition'}</DialogDescription></DialogHeader>{info&&<><p className="source-description">{info.note}</p><p className="source-description">Serving: {info.serving}. Amounts scale proportionally when you change quantity.</p>{info.nutritionDetails&&<dl className="nutrition-details">{info.nutritionDetails.map((d,i)=><div key={i}><dt>{d.label}</dt><dd>{d.value}{d.unit?` ${d.unit}`:''}</dd></div>)}</dl>}<a className="source-link" href={info.source} target="_blank" rel="noreferrer">Open nutrition source <ArrowUpRight size={16}/></a><button className="secondary-button" onClick={()=>{customize(info);setInfo(null)}}>Adjust for my order</button></>}</DialogContent></Dialog>
 <AlertDialog open={!!toDelete} onOpenChange={o=>{if(!o&&!deleting)setToDelete(null)}}><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Remove this meal?</AlertDialogTitle><AlertDialogDescription>{toDelete?.name} will be removed from your daily log and totals.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel disabled={deleting}>Keep meal</AlertDialogCancel><AlertDialogAction disabled={deleting} onClick={e=>{e.preventDefault();void remove()}}>{deleting?'Removing…':'Remove meal'}</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></>;
}
