import {z} from 'zod';
import {getChatGPTUser} from '@/app/chatgpt-auth';
import {database} from '@/db/raw';
export const dynamic='force-dynamic';
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(v=>!isNaN(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v);
const num=z.number().finite().min(0).max(20000);
const item=z.object({id:z.string().max(100),lineId:z.string().max(100),name:z.string().trim().min(1).max(160),restaurant:z.string().max(100),serving:z.string().trim().min(1).max(160),category:z.string().max(80),quality:z.enum(['published','estimate','custom']),source:z.string().max(2000).refine(v=>!v||/^https:\/\//.test(v)),note:z.string().max(2000),calories:num,protein:num,carbs:num,fat:num,quantity:z.number().finite().gt(0).max(100)});
const meal=z.object({id:z.string().uuid(),date,name:z.string().trim().min(1).max(160),period:z.enum(['Breakfast','Lunch','Dinner','Snack']),items:z.array(item).min(1).max(100)});
function reply(data:unknown,status=200){return Response.json(data,{status,headers:{'Cache-Control':'no-store'}})}
function decode(value:unknown){const r=value as Record<string,unknown>;return {id:r.id,date:r.date,name:r.name,period:r.period,items:JSON.parse(r.items as string),createdAt:r.created_at};}
export async function GET(req:Request){try{const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to load your food log.'},401);const d=date.safeParse(new URL(req.url).searchParams.get('date'));if(!d.success)return reply({error:'Choose a valid date.'},400);const db=database();const results=await db.batch([db.prepare('SELECT * FROM meals WHERE user_id = ? AND date = ? ORDER BY created_at DESC').bind(user.userId,d.data),db.prepare('SELECT * FROM meals WHERE user_id = ? ORDER BY created_at DESC LIMIT 12').bind(user.userId)]);return reply({meals:results[0].results.map(decode),recent:results[1].results.map(decode)});}catch(e){console.error('Load meals failed',e);return reply({error:'Your log could not load. Please try again.'},503)}}
export async function POST(req:Request){try{const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to save your meals.'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return reply({error:'Request origin is not allowed.'},403);const raw=await req.text();if(raw.length>150000)return reply({error:'This meal has too many details.'},413);let parsed;try{parsed=meal.safeParse(JSON.parse(raw))}catch{return reply({error:'Invalid meal.'},400)}if(!parsed.success)return reply({error:'Check the meal name, date, portions, and nutrition values.'},400);const m=parsed.data;await database().prepare('INSERT INTO meals (id,user_id,date,name,period,items,created_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(m.id,user.userId,m.date,m.name,m.period,JSON.stringify(m.items),Date.now()).run();return reply({id:m.id},201);}catch(e){console.error('Save meal failed',e);return reply({error:'Your meal could not save. Your draft is still here; please try again.'},503)}}
export async function DELETE(req:Request){try{const user=await getChatGPTUser();if(!user)return reply({error:'Sign in to update your log.'},401);const origin=req.headers.get('origin');if(origin&&origin!==new URL(req.url).origin)return reply({error:'Request origin is not allowed.'},403);const id=z.string().uuid().safeParse(new URL(req.url).searchParams.get('id'));if(!id.success)return reply({error:'Invalid meal.'},400);await database().prepare('DELETE FROM meals WHERE id = ? AND user_id = ?').bind(id.data,user.userId).run();return reply({ok:true});}catch(e){console.error('Delete meal failed',e);return reply({error:'This entry could not be removed. Please try again.'},503)}}
